# Generated by Django 6.0 on 2026-04-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('faculty', 'Faculty'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
